name: Checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  flake-check:
    runs-on: UbuntuLatest32Cores128G
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check Nix formatting
        run: |
          nix shell "https://flakehub.com/f/NixOS/nixpkgs/0.2411.715026#nixfmt-rfc-style" --command \
            sh -c "git ls-files '*.nix' | xargs nixfmt --check"

      - name: Check links in README
        run: |
          nix shell "https://flakehub.com/f/NixOS/nixpkgs/0.2411.715026#lychee" --command \
            lychee README.md
