name: Checks

on:
  pull_request:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  flake-check:
    runs-on: ubuntu-latest
    env:
      nixpkgs: "0.2505.810656"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main

      - name: Check Nix formatting
        run: |
          nix shell "https://flakehub.com/f/NixOS/nixpkgs/${{ env.nixpkgs }}#nixfmt-rfc-style" --command \
            sh -c "git ls-files '*.nix' | xargs nixfmt --check"

      - name: Check links in README
        run: |
          nix shell "https://flakehub.com/f/NixOS/nixpkgs/${{ env.nixpkgs }}#lychee" --command \
            lychee README.md
